on:
  pull_request:
    branches:
      - release/*
  push:
    branches:
      - release/*
      - e2e-testing
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install typescript runner
        run: pnpm i -g tsx
      - name: Install dependencies
        run: pnpm i
      - name: Run tests
        run: pnpm test
